# Generated by Django 5.1.1 on 2024-09-29 18:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id_ship', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ship_name', models.CharField(max_length=60)),
                ('class_name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=600)),
                ('status', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=255)),
                ('desc_img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id_parking', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 29, 21, 9, 33, 88120))),
                ('formed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('date_of_parking', models.DateField(null=True)),
                ('port', models.CharField(max_length=30)),
                ('moderator', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ParkingShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(max_length=50, null=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_ship', to='ships.parking')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.ship')),
            ],
            options={
                'db_table': 'parking_ship',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('parking', 'ship'), name='unique_parking_ship')],
            },
        ),
    ]
