# Generated by Django 5.1.2 on 2024-10-13 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 17, 34, 24, 835964)),
        ),
    ]
