# Generated by Django 5.1.1 on 2024-09-29 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 21, 18, 7, 775550)),
        ),
        migrations.AlterModelTable(
            name='parking',
            table='parking',
        ),
    ]
