# Generated by Django 5.1.2 on 2024-10-14 16:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_alter_parking_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 19, 11, 54, 777903)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='date_of_parking',
            field=models.DateField(default=datetime.date(2024, 10, 15), null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
