# Generated by Django 5.1.2 on 2024-10-14 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_alter_parking_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parkingship',
            name='unique_parking_ship',
        ),
        migrations.RenameField(
            model_name='parkingship',
            old_name='parking',
            new_name='id_parking',
        ),
        migrations.RenameField(
            model_name='parkingship',
            old_name='ship',
            new_name='id_ship',
        ),
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 19, 29, 41, 560376)),
        ),
        migrations.AddConstraint(
            model_name='parkingship',
            constraint=models.UniqueConstraint(fields=('id_parking', 'id_ship'), name='unique_parking_ship'),
        ),
    ]
