# Generated by Django 5.1.2 on 2024-10-14 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0004_remove_parkingship_unique_parking_ship_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parkingship',
            name='unique_parking_ship',
        ),
        migrations.RenameField(
            model_name='parkingship',
            old_name='id_parking',
            new_name='parking',
        ),
        migrations.RenameField(
            model_name='parkingship',
            old_name='id_ship',
            new_name='ship',
        ),
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 19, 31, 11, 906915)),
        ),
        migrations.AddConstraint(
            model_name='parkingship',
            constraint=models.UniqueConstraint(fields=('parking', 'ship'), name='unique_parking_ship'),
        ),
    ]
