# Generated by Django 5.1.2 on 2024-10-14 17:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0005_remove_parkingship_unique_parking_ship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 20, 14, 11, 677383)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='moderator',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
