# Generated by Django 5.1.2 on 2024-10-23 12:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0006_alter_parking_created_at_alter_parking_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 15, 4, 6, 258160)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='date_of_parking',
            field=models.DateField(default=datetime.date(2024, 10, 24), null=True),
        ),
        migrations.AlterField(
            model_name='parkingship',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_ship', to='ships.ship'),
        ),
    ]
