# Generated by Django 5.1.2 on 2024-10-23 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0007_alter_parking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='user_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 16, 53, 49, 165511)),
        ),
    ]
