# Generated by Django 5.1.2 on 2024-10-23 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0008_parking_user_name_alter_parking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='spendings_of_crew',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 17, 15, 20, 168738)),
        ),
    ]
